#ifndef claim_proofs_ffi_h
#define claim_proofs_ffi_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ScopeClaimProofData ScopeClaimProofData;

typedef struct CDDClaimData CDDClaimData;

typedef struct ScopeClaimData ScopeClaimData;

typedef struct Scalar Scalar;

typedef struct RistrettoPoint RistrettoPoint;

typedef struct Signature Signature;

typedef struct ProofPublicKey ProofPublicKey;

ScopeClaimProofData *build_scope_claim_proof_data_wrapper(const CDDClaimData *cdd_claim,
                                                          const ScopeClaimData *scope_claim);

void cdd_claim_data_free(CDDClaimData *ptr);

CDDClaimData *cdd_claim_data_new(Scalar *investor_did, Scalar *investor_unique_id);

RistrettoPoint *compute_cdd_id_wrapper(const CDDClaimData *cdd_claim);

RistrettoPoint *compute_scope_id_wrapper(const ScopeClaimData *scope_claim);

Signature *generate_id_match_proof_wrapper(ScopeClaimProofData *scope_claim_proof_data,
                                           const uint8_t *message,
                                           size_t message_size);

void proof_public_key_free(ProofPublicKey *ptr);

ProofPublicKey *proof_public_key_new(RistrettoPoint *cdd_id,
                                     Scalar *investor_did,
                                     RistrettoPoint *scope_id,
                                     Scalar *scope_did);

void scalar_free(Scalar *ptr);

Scalar *scalar_new(const uint8_t *scalar_bits, size_t len);

void scope_claim_data_free(ScopeClaimData *ptr);

ScopeClaimData *scope_claim_data_new(Scalar *scope_did, Scalar *investor_unique_id);

void scope_claim_proof_data_free(ScopeClaimProofData *ptr);

void signature_free(Signature *ptr);

bool verify_id_match_proof_wrapper(const ProofPublicKey *proof_public_key,
                                   const uint8_t *message,
                                   size_t message_size,
                                   const Signature *signature);

#endif /* claim_proofs_ffi_h */
