[package]
name = "polymesh-scv-v1"
version = "1.0.0"
authors = [ "Polymesh Association" ]
repository = "https://github.com/PolymeshAssociation/cryptography"
description = "Confidential Identity Library: Simple Claim Verifier"
edition = "2018"

[dependencies]
cli_common = { package = "confidential_identity_v1_cli_common", path = "../common/" }
confidential_identity_v1 = { path = "../.." }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# Crypto
schnorrkel = { version = "0.10", default-features = false, features = ["u64_backend"]}
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["alloc"] }

# Only binaries
structopt = { version = "0.3", default-features = false }

[features]
default = []

nightly = ["curve25519-dalek/nightly"]
