#ifndef private_identity_audit_ffi_h
#define private_identity_audit_ffi_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FinalProverResults FinalProverResults;

typedef struct InitialProverResults InitialProverResults;

/**
 * Holds the initial messages in the Zero-Knowledge Proofs sent by CDD Provider.
 */
typedef struct Proofs Proofs;

/**
 * Holds the CDD Provider's response to the PUIS challenge.
 */
typedef struct ProverFinalResponse ProverFinalResponse;

/**
 * Holds CDD Provider secret data.
 */
typedef struct ProverSecrets ProverSecrets;

/**
 * Holds PUIS secret data.
 */
typedef struct VerifierSecrets VerifierSecrets;

typedef struct VerifierSetGeneratorResults VerifierSetGeneratorResults;

typedef struct CddClaimData CddClaimData;

typedef struct Scalar Scalar;

typedef struct RistrettoPoint RistrettoPoint;

typedef struct CommittedUids CommittedUids;

/**
 * Create a new `CddClaimData` object.
 *
 * Caller is responsible for calling `cdd_claim_data_free()` to deallocate this object.
 * SAFETY: Caller is also responsible for making sure `investor_did` and
 *         `investor_unique_id` point to allocated blocks of memory of `investor_did_size`
 *         and `investor_unique_id_size` bytes respectively.
 */
CddClaimData *cdd_claim_data_new(const uint8_t *investor_did,
                                 size_t investor_did_size,
                                 const uint8_t *investor_unique_id,
                                 size_t investor_unique_id_size);

/**
 * Deallocates a `CddClaimData` object's memory.
 *
 * Should only be called on a still-valid pointer to an object returned by
 * `cdd_claim_data_new()`.
 */
void cdd_claim_data_free(CddClaimData *ptr);

void initial_prover_results_free(InitialProverResults *ptr);

InitialProverResults *generate_initial_proofs_wrapper(const CddClaimData *cdd_claim,
                                                      const uint8_t *seed,
                                                      size_t seed_size);

VerifierSetGeneratorResults *generate_committed_set_and_challenge_wrapper(Scalar *private_unique_identifiers,
                                                                          size_t private_unique_identifiers_size,
                                                                          const size_t *min_set_size,
                                                                          const uint8_t *seed,
                                                                          size_t seed_size);

FinalProverResults *generate_challenge_response_wrapper(ProverSecrets *secrets,
                                                        RistrettoPoint *committed_uids,
                                                        size_t committed_uids_size,
                                                        Scalar *challenge,
                                                        const uint8_t *seed,
                                                        size_t seed_size);

bool verify_proofs(const Proofs *initial_message,
                   const ProverFinalResponse *final_response,
                   Scalar *challenge,
                   RistrettoPoint *cdd_id,
                   const VerifierSecrets *verifier_secrets,
                   const CommittedUids *re_committed_uids);

#endif /* private_identity_audit_ffi_h */
