[package]
name = "mercat-interactive"
version = "1.0.0"
authors = [ "Polymath Inc" ]
edition = "2018"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "MERCAT account CLI for interacting with Polymesh chain."

[dependencies]
cryptography_core = { path = "../../../cryptography-core" }
mercat = { path = "../../../mercat" }
mercat_common = { package = "mercat-common", path = "../common/" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"]}
log = { version = "0.4.8"}
env_logger = { version = "0.7.1" }
structopt = { version = "0.3", default-features = false }
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }
base64 = { version = "0.12.1" }
failure = { version = "0.1.7" }

# Crypto
rand = { version = "0.7.3", features = ["wasm-bindgen", "getrandom", "alloc"], default-features = false }
hex = { version = "0.4.2" }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["nightly", "alloc"] }
