[package]
name = "polymath-scp-v2"
version = "1.0.0"
authors = [ "Polymesh Association" ]
repository = "https://github.com/PolymeshAssociation/cryptography"
description = "Confidential Identity Library: Simple Claim Prover"
edition = "2018"

[dependencies]
cli_common = { package = "confidential_identity_v2_cli_common", path = "../common/" }
confidential_identity_v2 = { path = "../../" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

# Crypto
rand = { version = "0.8", features = ["getrandom", "alloc"], default-features = false }
rand_core = { version = "0.6", default-features = false}
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["alloc"] }

# Only binaries
structopt = { version = "0.3", default-features = false }

[features]
default = []

nightly = ["curve25519-dalek/nightly"]
