#! /bin/bash

set -eo pipefail

if [ "$#" -ne 3 ]; then
    echo "$0 <PROJECT_NAME> <SRC_DIR> <DST_DIR>"
    exit 1
fi

PROJECT_NAME="$1"
SRC_DIR="$2"
DST_DIR="$3"

echo "Building npm package from $SRC_DIR to $DST_DIR"

rm -rf "$DST_DIR"
mkdir -p "$DST_DIR"
cd "$SRC_DIR"

# Inherit the root level license
cp "$ROOT/LICENSE" .

# Build the npm package
wasm-pack build --release

# Change the autogenerated name to have @polymathnetwork as a prefix
GET_VERSION_PY='import json,sys;print json.load(sys.stdin)["name"]'
NAME=$(cat pkg/packages.json | python -c "$GET_VERSION_PY")
SET_VERSION_PY="import json,sys; obj = json.load(sys.stdin); obj[\"name\"]=\"@polymathnetwork/${NAME}\"; print(json.dumps(obj, sort_keys=True, indent=4, separators=(',', ': ')))"
$(cat pkg/packages.json | SET_VERSION_PY > pkg/packages.json)

# Move to the artifact directory
cp -r pkg/* "$DST_DIR"
