[package]
name = "mercat-common"
version = "1.0.0"
authors = [ "Polymath Inc" ]
edition = "2018"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "MERCAT CLI common library."

[dependencies]
cryptography_core = { path = "../../../cryptography-core" }
mercat = { path = "../../../mercat" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", features = ["alloc"] }
serde_bytes = { version = "0.11", features = ["alloc"] }
log = { version = "0.4.8" }
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }
failure = { version = "0.1.7" }
base64 = { version = "0.12.1" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
yaml-rust = { version = "0.4" }
linked-hash-map= { version = "0.5.3" }
regex = { version = "1.3.9" }

# Crypto
rand = { version = "0.8", features = ["getrandom", "alloc"] }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["nightly", "alloc"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.10"
env_logger = { version = "0.7.1" }
