[package]
name = "mercat-common"
version = "1.1.0"
authors = [ "Polymesh Association" ]
edition = "2018"
repository = "https://github.com/PolymeshAssociation/cryptography"
description = "MERCAT CLI common library."

[dependencies]
confidential_identity_core = { version = "1.1.2", path = "../../../confidential-identity-core", default-features = false }
mercat = { version = "1.1.2",  path = "../../../mercat", default-features = false }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", features = ["alloc"] }
serde_bytes = { version = "0.11", features = ["alloc"] }
log = { version = "0.4.8" }
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }
failure = { version = "0.1.7" }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
yaml-rust = { version = "0.4" }
linked-hash-map= { version = "0.5.3" }
regex = { version = "1.6" }

# Crypto
rand = { version = "0.8", features = ["getrandom", "alloc"], default-features = false }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["alloc"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.10"
env_logger = { version = "0.7.1" }

[features]
default = ["std", "mercat/u64_backend"]

nightly = ["curve25519-dalek/nightly"]

std = [
	"confidential_identity_core/std",
	"metrics/std",
	"mercat/std",
]
