[package]
name = "confidential_identity_v1_cli_common"
version = "1.0.0"
authors = [ "Polymesh Association" ]
edition = "2018"
repository = "https://github.com/PolymeshAssociation/cryptography"
description = "Confidential Identity Library: CLI common library"

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"]}

# Crypto
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["alloc"] }
blake2 = { version = "0.10.2", default-features = false }
