[package]
name = "mercat-chain-setup"
version = "1.0.0"
authors = [ "Polymesh Association" ]
edition = "2018"
repository = "https://github.com/PolymeshAssociation/cryptography"
description = "MERCAT CLI for preping the data on the \"chain\" for a successful run of other MERCAT CLIs"

[dependencies]
cryptography_core = { path = "../../../cryptography-core" }
mercat = { path = "../../../mercat" }
mercat_common = { package = "mercat-common", path = "../common/" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"]}
log = { version = "0.4.8"}
env_logger = { version = "0.7.1" }
confy = { version = "0.4.0" }
structopt = { version = "0.3", default-features = false }
metrics = { version = "0.12.1" }
metrics-core = { version = "0.5.2" }
base64 = { version = "0.12.1" }
failure = { version = "0.1.7" }

# Crypto
rand = { version = "0.8", features = ["getrandom", "alloc"], default-features = false }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["nightly", "alloc"] }
